// 出題される英語のリスト（小学生向け・簡単な表現）
// en: 出題文 / jp: 日本語訳（表示用）
const SENTENCES = [
  { en: "Hello.", jp: "こんにちは。" },
  { en: "Hi, how are you?", jp: "やあ、げんき？" },
  { en: "I'm happy.", jp: "わたしは うれしいです。" },
  { en: "I'm fine, thank you.", jp: "げんきです、ありがとう。" },
  { en: "Do you like baseball?", jp: "やきゅうは すきですか？" },
  { en: "I like soccer.", jp: "わたしは サッカーが すきです。" },
  { en: "I can play the piano.", jp: "わたしは ピアノが ひけます。" },
  { en: "I can swim.", jp: "わたしは およげます。" },
  { en: "I can't fly.", jp: "わたしは とべません。" },
  { en: "What's this?", jp: "これは なに？" },
  { en: "This is a pen.", jp: "これは ペンです。" },
  { en: "I want to be a teacher.", jp: "わたしは せんせいに なりたいです。" },
  { en: "My favorite color is blue.", jp: "すきな いろは あおです。" },
  { en: "What color do you like?", jp: "どんな いろが すきですか？" },
  { en: "I have a dog.", jp: "わたしは いぬを かっています。" },
  { en: "Where is the library?", jp: "としょかんは どこですか？" },
  { en: "Turn right.", jp: "みぎに まがってね。" },
  { en: "Turn left.", jp: "ひだりに まがってね。" },
  { en: "Go straight.", jp: "まっすぐ すすんでね。" },
  { en: "What time is it?", jp: "いま なんじですか？" },
  { en: "It's three o'clock.", jp: "3じです。" },
  { en: "I'm hungry.", jp: "おなかが すきました。" },
  { en: "I'm sleepy.", jp: "ねむいです。" },
  { en: "Nice to meet you.", jp: "はじめまして。" },
  { en: "See you tomorrow.", jp: "また あした！" },
  { en: "Thank you very much.", jp: "どうも ありがとう。" },
  { en: "You're welcome.", jp: "どういたしまして。" },
  { en: "How many apples do you have?", jp: "りんごを いくつ もっていますか？" },
  { en: "I have two apples.", jp: "りんごを 2つ もっています。" },
  { en: "What day is it today?", jp: "きょうは なんようびですか？" },
  { en: "It's Monday.", jp: "げつようびです。" },
  { en: "I want an apple.", jp: "りんごが ほしいです。" },
  { en: "Can I have some water?", jp: "おみずを もらえますか？" },
  { en: "Let's play tag.", jp: "おにごっこを しよう。" },
  { en: "It's sunny today.", jp: "きょうは はれです。" },
  { en: "It's raining.", jp: "あめが ふっています。" },
  { en: "I like ice cream.", jp: "わたしは アイスクリームが すきです。" },
  { en: "What's your name?", jp: "おなまえは なんですか？" },
  { en: "My name is Ken.", jp: "わたしの なまえは けんです。" },
  { en: "Good morning.", jp: "おはようございます。" },
  { en: "Good night.", jp: "おやすみなさい。" },
  { en: "Goodbye.", jp: "さようなら。" },
  { en: "I like dogs.", jp: "わたしは いぬが すきです。" },
  { en: "This is my bag.", jp: "これは わたしの かばんです。" },
  { en: "I'm a good singer.", jp: "わたしは うたが じょうずです。" },
  { en: "Let's go to the park.", jp: "こうえんに いこう。" },
];

// ランキング用のプレイヤー名（かわいい名前をランダムで作る）
// 形容詞パターン × なまえパターン ＝ たくさんの組み合わせ
const NAME_ADJECTIVES = [
  "げんきな", "きらきらの", "ぴかぴかの", "もこもこの", "ふわふわの",
  "にこにこの", "わくわくの", "どきどきの", "ちびっこ", "スーパー",
  "パワフルな", "ゆかいな", "おちゃめな", "かわいい", "かっこいい",
  "つよい", "はやい", "ゆうかんな", "ひみつの", "まほうの",
  "きんいろの", "ぎんいろの", "にじいろの", "ほしくずの", "たいようの",
  "つきの", "かぜの", "みずの", "ほのおの", "こおりの",
  "でんきの", "レインボーの", "スイートな", "クールな", "ホットな",
  "スマイルの", "ラッキーな", "おおきな", "ちいさな", "さいきょうの",
  "てんさいの", "ゆうめいな", "にんきの", "うたじょうずな", "はしるのがはやい",
  "げんきいっぱいの", "たのしい", "ゆめみる", "ぶっとびの", "とびきりの"
];

const NAME_NOUNS = [
  "パンダ", "ライオン", "とら", "ぞう", "うさぎ",
  "ねこ", "いぬ", "きつね", "くま", "ペンギン",
  "いるか", "さめ", "ふくろう", "たか", "りゅう",
  "ユニコーン", "にんじゃ", "ヒーロー", "おうじ", "おひめさま",
  "まほうつかい", "かいぞく", "うちゅうひこうし", "ロボット", "にじ",
  "ほし", "つき", "たいよう", "ケーキ", "いちご",
  "りんご", "バナナ", "アイス", "ドーナツ", "キャンディ",
  "ロケット", "ひこうき", "でんしゃ", "サッカーボール", "ギター",
  "ピアノ", "たこ", "かに", "かめ", "コアラ",
  "かっぱ", "てんし", "おばけ", "ドラゴン", "せんし"
];
